### ISSUE TITLE
Add shell build script

### ISSUE THREAD

**Issue by kswirydo** [Exawind/hypre-mini-app#2]
-[ ] add shell build script:
What worked for me:
get interactive node
module use /nopt/nrel/ecom/ecp/base/modules/gcc-5.2.0/
module load gcc/5.2.0 cmake binutils openmpi hypre
mkdir build
cd build
cmake -DHYPRE_DIR={HYPRE_INSTALL_DIR} ../
make -j 4

**Comment by sayerhs** [comment]
Addressed in 650366867520
